# **Pandas**
- Pandas is a Python library used for

    1.   Data Analysis
    2.   Data Cleaning
    3.   Data Manipulation
    4.   Data Preprocessing
    5.   Working with CSV or Excel data

**Insert Library :** `**import pandas as pd**`

# **DataFrame**
- A dataframe is a **two-dimensional table** consisting of:

*   **Rows**
*   **Columns**

# **Create a DataFrame**

In [3]:
import pandas as pd
student = {
    "Name" : ["Alice", "John", "Julia"],
    "Age" : [20, 21, 22],
    "Mark" : [85, 90, 75]
}

df = pd.DataFrame(student)
print(df)

    Name  Age  Mark
0  Alice   20    85
1   John   21    90
2  Julia   22    75

# **Reading CSV Data**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/disease_data.csv")
print(df)

    Age  BloodPressure  BloodSugar  Cholesterol  Disease
0    25            110          90          170        0
1    30            115          95          180        0
2    35            120         100          190        0
3    40            125         110          200        1
4    45            130         120          210        1
5    50            135         130          220        1
6    55            140         140          230        1
7    60            145         150          240        1
8    28            112          92          175        0
9    32            118          98          185        0
10   38            122         105          195        0
11   42            128         115          205        1
12   48            132         125          215        1
13   53            138         135          225        1
14   58            142         145          235        1
15   65            150         155          250        1

# **View First Rows**

In [5]:
#head() displays the first 5 rows by defult
df.head()

   Age  BloodPressure  BloodSugar  Cholesterol  Disease
0   25            110          90          170        0
1   30            115          95          180        0
2   35            120         100          190        0
3   40            125         110          200        1
4   45            130         120          210        1

# **View Last Rows**

In [6]:
df.tail()

    Age  BloodPressure  BloodSugar  Cholesterol  Disease
11   42            128         115          205        1
12   48            132         125          215        1
13   53            138         135          225        1
14   58            142         145          235        1
15   65            150         155          250        1

In [7]:
df.tail(7)

    Age  BloodPressure  BloodSugar  Cholesterol  Disease
9    32            118          98          185        0
10   38            122         105          195        0
11   42            128         115          205        1
12   48            132         125          215        1
13   53            138         135          225        1
14   58            142         145          235        1
15   65            150         155          250        1

# **Check Data Information**
- display important information
    - how many rows and columns
    - what are column's names
    - data type
    - missing value

In [9]:
#check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            16 non-null     int64
 1   BloodPressure  16 non-null     int64
 2   BloodSugar     16 non-null     int64
 3   Cholesterol    16 non-null     int64
 4   Disease        16 non-null     int64
dtypes: int64(5)
memory usage: 772.0 bytes

In [11]:
#check data shape - display size of DataFrame(how many rows and columns)
df.shape #not function

(16, 5)

In [13]:
#get column names
df.columns

Index(['Age', 'BloodPressure', 'BloodSugar', 'Cholesterol', 'Disease'], dtype='object')

In [16]:
#statistical summary
# describe() - statistical information such as count, mean, standard devision, minimum and maximum
df.describe()

             Age  BloodPressure  BloodSugar  Cholesterol  Disease
count  16.000000      16.000000   16.000000    16.000000   16.000
mean   44.000000     128.875000  119.062500   207.812500    0.625
std    12.225656      12.186741   21.647074    24.356296    0.500
min    25.000000     110.000000   90.000000   170.000000    0.000
25%    34.250000     119.500000   99.500000   188.750000    0.000
50%    43.500000     129.000000  117.500000   207.500000    1.000
75%    53.500000     138.500000  136.250000   226.250000    1.000
max    65.000000     150.000000  155.000000   250.000000    1.000

In [21]:
#select a column
df['BloodPressure']

0     110
1     115
2     120
3     125
4     130
5     135
6     140
7     145
8     112
9     118
10    122
11    128
12    132
13    138
14    142
15    150
Name: BloodPressure, dtype: int64

In [23]:
#select
df[['Age', 'BloodPressure']]

    Age  BloodPressure
0    25            110
1    30            115
2    35            120
3    40            125
4    45            130
5    50            135
6    55            140
7    60            145
8    28            112
9    32            118
10   38            122
11   42            128
12   48            132
13   53            138
14   58            142
15   65            150